name: Generate Datas

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Snake Animation
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: adityababar07
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist

